import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import SignUpModal from "@/components/SignUpModal";
import LoginModal from "@/components/LoginModal";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "KaizenShop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LoginModal/>
        <SignUpModal/>
        <Header/>
        <Suspense>
          {children}
        </Suspense>
        <Footer/>
        <Toaster
          richColors  
          position="top-right"
          expand={false}
         />
      </body>
    </html>
  );
}
