import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer, Bounce } from 'react-toastify';
import { Suspense } from "react";
/* import Banner from "@/components/Banner";
import LoginModal from "@/components/LoginModal";
import SignUpModal from "@/components/SignUpModal"; */



export const metadata: Metadata = {
  title: "KaizenShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ToastContainer
        position="bottom-right"
        autoClose={5000}
        hideProgressBar
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        transition={Bounce}
        />
        {/* <Banner/> */}
        {/* <LoginModal/> */}
        {/* <SignUpModal/> */}
        <Header/>
        <Suspense>
          {children}
        </Suspense>
        <Footer/>
      </body>
    </html>
  );
}
