import { Metadata } from "next";
import Shop from "./Shop";

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

const ShopPage = () => {
  const params = { category: "all" };
  return <Shop params={params} />
};
export default ShopPage;
